In [10]:
import geopandas as gpd
import sys
import os
from shapely import MultiPolygon, Polygon
sys.path.append('/home/pedro/Documents/GIT_WORKSPACE/split_offdb')
os.chdir('/home/pedro/Documents/GIT_WORKSPACE/split_offdb')
from split import Splitter
from rtree import index
import time
from shapely.strtree import STRtree
from geopandas.tools import sjoin
import pandas as pd
from multiprocessing import Pool
from joblib import Parallel, delayed
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import shapely as shp
from shapely.geometry import MultiLineString, LineString, Polygon, MultiPolygon, LinearRing

In [2]:
grid=gpd.read_parquet('/home/pedro/Documents/GIT_WORKSPACE/split_offdb/inputs/grid.parquet')

grid.rename(columns={'grid_id':'id'}, inplace=True)

grid

        id                                               geom
0        1  POLYGON ((-74 -34, -74 -33.5, -73.5 -33.5, -73...
1        2  POLYGON ((-74 -33.5, -74 -33, -73.5 -33, -73.5...
2        3  POLYGON ((-74 -33, -74 -32.5, -73.5 -32.5, -73...
3        4  POLYGON ((-74 -32.5, -74 -32, -73.5 -32, -73.5...
4        5  POLYGON ((-74 -32, -74 -31.5, -73.5 -31.5, -73...
...    ...                                                ...
7184  7185  POLYGON ((-29 3, -29 3.5, -28.5 3.5, -28.5 3, ...
7185  7186  POLYGON ((-29 3.5, -29 4, -28.5 4, -28.5 3.5, ...
7186  7187  POLYGON ((-29 4, -29 4.5, -28.5 4.5, -28.5 4, ...
7187  7188  POLYGON ((-29 4.5, -29 5, -28.5 5, -28.5 4.5, ...
7188  7189  POLYGON ((-29 5, -29 5.5, -28.5 5.5, -28.5 5, ...

[7189 rows x 2 columns]

In [6]:
splitter=Splitter()
engine = create_engine('postgresql://paq_coutinho:1Kakaroto*@localhost:5432/funbio')

In [ ]:
splitter._intersection_sql(grid_gdf=grid, n_grid=367, engine=engine

ERROR:root:Nâo foi possivel formar o MultiLinestring pelo motivo TopologyException: Iterated noding failed to converge after 6 iterations (near -71.536 -8.93541)

'0.19'

In [30]:
##prepare split line funcion
splitter.counter=0
start_time=time.time()

"""Essa funcao é a mais complicada do código
O que ela se propõe a fazer é simples: Gerar uma MultiLinestring que será inputada no shp.node()
Essa multilinestring deve ser construída da maneira mais manual possível"""

try:
    linerings=[]
    #Temos que forçar que todos os poligonos de entrada devem formar lines rings. Caso isso não seja possível a geometria deve ser descartada pois vai dar BO
    for index, row in splitter.gdf_input_intersection.iterrows():
        #Seleciona geometria do dado
        geom=row.geom           
        #Se for multipolygon, seleciona o primeiro polygon da feição e pega o boundary. 
        # Aqui todas as geometria sao validas
        if isinstance(geom, MultiPolygon):   
            geom= geom.geoms[0] 
            line=geom.exterior
        elif isinstance(geom, Polygon):
            geom = geom
            line=geom.exterior # A funcao exterior é um sacada, ao invés de usar a boundary. Ler documentacao para compreender.

        #Se a linha capturada for válida, appenda na lista de linearRings, se não for válida, joga no lixo pelo bem da humanidade
        if line.is_valid:
            line=LinearRing(line)
            linerings.append(line)
        else:
            splitter.counter+=1
            #print(f"Feição descartada - ID: {row['id']}, ID Layer: {row['name']}, Geometria: {geom}")
            #passa pro promixo loop e nao appenda
            continue   

    




         
    #Esse try é crítico. As tres próximas linhas são onde mais ocorre erro, principalmente a função node que ainda é um certo mistério
    # como funciona. 
    try:            
        #Appenda o grid, para que seja feita a reconstrucao total do grid
        linerings.append(LinearRing(splitter.unidade_split.exterior))
        #Cria um MultiLineString a partir de todas as linhas
        multi_line=MultiLineString(linerings)       
        #Cria o MultiLineString com nós onde as linhas se cruzam
        splitter.multi_line_with_nodes=shp.unary_union(multi_line)        

    except Exception as e:
        #Caso ocorra algum exception, o grid é pulado
        print(f'Nâo foi possivel formar o MultiLinestring pelo motivo {e}')

except Exception as e:
    print(f'Função prepare_split_line na iteração {splitter.n_grid} deu o problema {e}')

elapsed_time=time.time()-start_time

splitter.multi_line_with_nodes

In [31]:
splitter.perform_split()

'0.11'

In [32]:
##Overlap function
if "representative_point" not in splitter.gdf_broken_glass.columns:
    splitter.gdf_broken_glass["representative_point"] = splitter.gdf_broken_glass.geometry.apply(lambda x: x.representative_point())


for index, row in splitter.gdf_broken_glass.iterrows():
    
    try:
        print(f"ID: {row['id']}")
        idx, shard_data = row.name, row
        glass_shard_point = shard_data["representative_point"]
        nearest_index = splitter.spatial_index.query_nearest(glass_shard_point)
        nearest_polygon = splitter.gdf_input_intersection.iloc[nearest_index]

        #Resetar indice é importante
        nearest_polygon.reset_index(drop=False, inplace = True)

        idx_true_intersection = []
        #Etapa de maior consumo de processador e memoria. Deve ser feito em iteração sequencial. Cada polígono do CAR deve ser
        # testado para sobreposicao com o representative point (glass_shard_point)
        for idx, row in nearest_polygon.iterrows():
            try:
                if row.geom.intersects(glass_shard_point):
                    
                    idx_true_intersection.append(idx)
            except:
                pass
        #Por isso precisa resetar indice
        true_intersection = nearest_polygon.iloc[idx_true_intersection]        

        # Se estiver vazio, retorna apenas id_do grid e id_layer="GRID". Podem ocorrer grids vazios a depender do INPUT.
        # Se não, retorna a lista com os id envolvidos
        if not true_intersection.empty:
            id_layers = ['GRID'] + true_intersection["id_layer"].tolist()
            id_features = [splitter.n_grid] + true_intersection["id"].tolist()
        else:
            id_layers = ['GRID']
            id_features = [splitter.n_grid]

    except:
       
        break

ID: 1
ID: 2
ID: 3
ID: 4
ID: 5
ID: 6
ID: 7
ID: 8
ID: 9
ID: 10
ID: 11
ID: 12
ID: 13
ID: 14
ID: 15
ID: 16
ID: 17
ID: 18
ID: 19
ID: 20
ID: 21
ID: 22
ID: 23
ID: 24
ID: 25
ID: 26
ID: 27
ID: 28
ID: 29
ID: 30
ID: 31
ID: 32
ID: 33
ID: 34
ID: 35
ID: 36
ID: 37
ID: 38
ID: 39
ID: 40
ID: 41
ID: 42
ID: 43
ID: 44
ID: 45
ID: 46
ID: 47
ID: 48
ID: 49
ID: 50
ID: 51
ID: 52
ID: 53
ID: 54
ID: 55
ID: 56
ID: 57
ID: 58
ID: 59
ID: 60
ID: 61
ID: 62
ID: 63
ID: 64
ID: 65
ID: 66
ID: 67
ID: 68
ID: 69
ID: 70
ID: 71
ID: 72
ID: 73
ID: 74
ID: 75
ID: 76
ID: 77
ID: 78
ID: 79
ID: 80
ID: 81
ID: 82
ID: 83
ID: 84
ID: 85
ID: 86
ID: 87
ID: 88
ID: 89
ID: 90
ID: 91
ID: 92
ID: 93
ID: 94
ID: 95
ID: 96
ID: 97
ID: 98
ID: 99
ID: 100
ID: 101
ID: 102
ID: 103
ID: 104
ID: 105
ID: 106
ID: 107
ID: 108
ID: 109
ID: 110
ID: 111
ID: 112
ID: 113
ID: 114
ID: 115
ID: 116
ID: 117
ID: 118
ID: 119
ID: 120
ID: 121
ID: 122
ID: 123
ID: 124
ID: 125
ID: 126
ID: 127
ID: 128
ID: 129
ID: 130
ID: 131
ID: 132
ID: 133
ID: 134
ID: 135
ID: 136
ID: 137
ID: 138
ID: 139
ID: 140
ID: 141
ID: 142
ID: 143
ID: 144
ID: 145
ID: 146
ID: 147
ID: 148
ID: 149
ID: 150
ID: 151
ID: 152
ID: 153
ID: 154
ID: 155
ID: 156
ID: 157
ID: 158
ID: 159
ID: 160
ID: 161
ID: 162
ID: 163
ID: 164
ID: 165
ID: 166
ID: 167
ID: 168
ID: 169
ID: 170
ID: 171
ID: 172
ID: 173
ID: 174
ID: 175
ID: 176
ID: 177
ID: 178
ID: 179
ID: 180
ID: 181
ID: 182
ID: 183
ID: 184
ID: 185
ID: 186
ID: 187
ID: 188
ID: 189
ID: 190
ID: 191
ID: 192
ID: 193
ID: 194
ID: 195
ID: 196
ID: 197
ID: 198
ID: 199
ID: 200
ID: 201
ID: 202
ID: 203
ID: 204
ID: 205
ID: 206
ID: 207
ID: 208
ID: 209
ID: 210
ID: 211
ID: 212
ID: 213
ID: 214
ID: 215
ID: 216
ID: 217
ID: 218
ID: 219
ID: 220
ID: 221
ID: 222
ID: 223
ID: 224
ID: 225
ID: 226
ID: 227
ID: 228
ID: 229
ID: 230
ID: 231
ID: 232
ID: 233
ID: 234
ID: 235
ID: 236
ID: 237
ID: 238
ID: 239
ID: 240
ID: 241
ID: 242
ID: 243
ID: 244
ID: 245
ID: 246
ID: 247
ID: 248
ID: 249
ID: 250
ID: 251
ID: 252
ID: 253
ID: 254
ID: 255
ID: 256
ID: 257
ID: 258
ID: 259
ID: 260
ID: 261
ID: 262
ID: 263
ID: 264
ID: 265
ID: 266
ID: 267
ID: 268
ID: 269
ID: 270
ID: 271
ID: 272
ID: 273
ID: 274
ID: 275
ID: 276
ID: 277
ID: 278
ID: 279
ID: 280
ID: 281
ID: 282
ID: 283
ID: 284
ID: 285
ID: 286
ID: 287
ID: 288
ID: 289
ID: 290
ID: 291
ID: 292
ID: 293
ID: 294
ID: 295
ID: 296
ID: 297
ID: 298
ID: 299
ID: 300
ID: 301
ID: 302
ID: 303
ID: 304
ID: 305
ID: 306
ID: 307
ID: 308
ID: 309
ID: 310
ID: 311
ID: 312
ID: 313
ID: 314
ID: 315
ID: 316
ID: 317
ID: 318
ID: 319
ID: 320
ID: 321
ID: 322
ID: 323
ID: 324
ID: 325
ID: 326
ID: 327
ID: 328
ID: 329
ID: 330
ID: 331
ID: 332
ID: 333
ID: 334
ID: 335
ID: 336
ID: 337
ID: 338
ID: 339
ID: 340
ID: 341
ID: 342
ID: 343
ID: 344
ID: 345
ID: 346
ID: 347
ID: 348
ID: 349
ID: 350
ID: 351
ID: 352
ID: 353
ID: 354
ID: 355
ID: 356
ID: 357
ID: 358
ID: 359
ID: 360
ID: 361
ID: 362
ID: 363
ID: 364
ID: 365
ID: 366
ID: 367
ID: 368
ID: 369
ID: 370
ID: 371
ID: 372
ID: 373
ID: 374
ID: 375
ID: 376
ID: 377
ID: 378
ID: 379
ID: 380
ID: 381
ID: 382
ID: 383
ID: 384
ID: 385
ID: 386
ID: 387
ID: 388
ID: 389
ID: 390
ID: 391
ID: 392
ID: 393
ID: 394
ID: 395
ID: 396
ID: 397
ID: 398
ID: 399
ID: 400
ID: 401
ID: 402
ID: 403
ID: 404
ID: 405
ID: 406
ID: 407
ID: 408
ID: 409
ID: 410
ID: 411
ID: 412
ID: 413
ID: 414
ID: 415
ID: 416
ID: 417
ID: 418
ID: 419
ID: 420
ID: 421
ID: 422
ID: 423
ID: 424
ID: 425
ID: 426
ID: 427
ID: 428
ID: 429
ID: 430
ID: 431
ID: 432
ID: 433
ID: 434
ID: 435
ID: 436
ID: 437
ID: 438
ID: 439
ID: 440
ID: 441
ID: 442
ID: 443
ID: 444
ID: 445
ID: 446
ID: 447
ID: 448
ID: 449
ID: 450
ID: 451
ID: 452
ID: 453
ID: 454
ID: 455
ID: 456
ID: 457
ID: 458
ID: 459
ID: 460
ID: 461
ID: 462
ID: 463
ID: 464
ID: 465
ID: 466
ID: 467
ID: 468
ID: 469
ID: 470
ID: 471
ID: 472
ID: 473
ID: 474
ID: 475
ID: 476
ID: 477
ID: 478
ID: 479
ID: 480
ID: 481
ID: 482
ID: 483
ID: 484
ID: 485
ID: 486
ID: 487
ID: 488
ID: 489
ID: 490
ID: 491
ID: 492
ID: 493
ID: 494
ID: 495
ID: 496
ID: 497
ID: 498
ID: 499
ID: 500
ID: 501
ID: 502
ID: 503
ID: 504
ID: 505
ID: 506
ID: 507
ID: 508
ID: 509
ID: 510
ID: 511
ID: 512
ID: 513
ID: 514
ID: 515
ID: 516
ID: 517
ID: 518
ID: 519
ID: 520
ID: 521
ID: 522
ID: 523
ID: 524
ID: 525
ID: 526
ID: 527
ID: 528
ID: 529
ID: 530
ID: 531
ID: 532
ID: 533
ID: 534
ID: 535
ID: 536
ID: 537
ID: 538
ID: 539
ID: 540
ID: 541
ID: 542
ID: 543
ID: 544
ID: 545
ID: 546
ID: 547
ID: 548
ID: 549
ID: 550
ID: 551
ID: 552
ID: 553
ID: 554
ID: 555
ID: 556
ID: 557
ID: 558
ID: 559
ID: 560
ID: 561
ID: 562
ID: 563
ID: 564
ID: 565
ID: 566
ID: 567
ID: 568
ID: 569
ID: 570
ID: 571
ID: 572
ID: 573
ID: 574
ID: 575
ID: 576
ID: 577
ID: 578
ID: 579
ID: 580
ID: 581
ID: 582
ID: 583
ID: 584
ID: 585
ID: 586
ID: 587
ID: 588
ID: 589
ID: 590
ID: 591
ID: 592
ID: 593
ID: 594
ID: 595
ID: 596
ID: 597
ID: 598
ID: 599
ID: 600
ID: 601
ID: 602
ID: 603
ID: 604
ID: 605
ID: 606
ID: 607
ID: 608
ID: 609
ID: 610
ID: 611
ID: 612
ID: 613
ID: 614
ID: 615
ID: 616
ID: 617
ID: 618
ID: 619
ID: 620
ID: 621
ID: 622
ID: 623
ID: 624
ID: 625
ID: 626
ID: 627
ID: 628
ID: 629
ID: 630
ID: 631
ID: 632
ID: 633
ID: 634
ID: 635
ID: 636
ID: 637
ID: 638
ID: 639
ID: 640
ID: 641
ID: 642
ID: 643
ID: 644
ID: 645
ID: 646
ID: 647
ID: 648
ID: 649
ID: 650
ID: 651
ID: 652
ID: 653
ID: 654
ID: 655
ID: 656
ID: 657
ID: 658
ID: 659
ID: 660
ID: 661
ID: 662
ID: 663
ID: 664
ID: 665
ID: 666
ID: 667
ID: 668
ID: 669
ID: 670
ID: 671
ID: 672
ID: 673
ID: 674
ID: 675
ID: 676
ID: 677
ID: 678
ID: 679
ID: 680
ID: 681
ID: 682
ID: 683
ID: 684
ID: 685
ID: 686
ID: 687
ID: 688
ID: 689
ID: 690
ID: 691
ID: 692
ID: 693
ID: 694
ID: 695
ID: 696
ID: 697
ID: 698
ID: 699
ID: 700
ID: 701
ID: 702
ID: 703
ID: 704
ID: 705
ID: 706
ID: 707
ID: 708
ID: 709
ID: 710
ID: 711
ID: 712
ID: 713
ID: 714
ID: 715
ID: 716
ID: 717
ID: 718
ID: 719
ID: 720
ID: 721
ID: 722
ID: 723
ID: 724
ID: 725
ID: 726
ID: 727
ID: 728
ID: 729
ID: 730
ID: 731
ID: 732
ID: 733
ID: 734
ID: 735
ID: 736
ID: 737
ID: 738
ID: 739
ID: 740
ID: 741
ID: 742
ID: 743
ID: 744
ID: 745
ID: 746
ID: 747
ID: 748
ID: 749
ID: 750
ID: 751
ID: 752
ID: 753
ID: 754
ID: 755
ID: 756
ID: 757
ID: 758
ID: 759
ID: 760
ID: 761
ID: 762
ID: 763
ID: 764
ID: 765
ID: 766
ID: 767
ID: 768
ID: 769
ID: 770
ID: 771
ID: 772
ID: 773
ID: 774
ID: 775
ID: 776
ID: 777
ID: 778
ID: 779
ID: 780
ID: 781
ID: 782
ID: 783
ID: 784
ID: 785
ID: 786
ID: 787
ID: 788
ID: 789

KeyError: 'id_feature'

In [37]:

nearest_index = splitter.spatial_index.query_nearest(splitter.gdf_broken_glass["representative_point"][3])
nearest_index
nearest_polygon = splitter.gdf_input_intersection.iloc[nearest_index]

nearest_polygon.reset_index(drop=False, inplace = True)

idx_true_intersection = []

#Etapa de maior ineficiencia. Minimizada...
for idx, row in nearest_polygon.iterrows():
    if row.geom.intersects(splitter.gdf_broken_glass['representative_point'][3]):
        idx_true_intersection.append(idx)

nearest_polygon = nearest_polygon.iloc[idx_true_intersection] 
nearest_polygon

Empty GeoDataFrame
Columns: [index, id, id_layer, geom]
Index: []

In [36]:

row.geom.intersects(splitter.gdf_broken_glass['representative_point'][3])

False

In [23]:
splitter.gdf_broken_glass

    id                                           geometry
0    1  POLYGON ((-62.61852 -13.0144, -62.61762 -13.01...
1    2  POLYGON ((-62.62208 -13.01771, -62.61762 -13.0...
2    3  POLYGON ((-62.62208 -13.01771, -62.62272 -13.0...
3    4  POLYGON ((-62.62345 -13.01771, -62.62272 -13.0...
4    5  POLYGON ((-62.5 -13.08081, -62.504 -13.08071, ...
5    6  POLYGON ((-62.61456 -13.02859, -62.61415 -13.0...
6    7  POLYGON ((-62.61456 -13.02859, -62.61461 -13.0...
7    8  POLYGON ((-62.61251 -13.02531, -62.61284 -13.0...
8    9  POLYGON ((-62.61251 -13.02531, -62.61041 -13.0...
9   10  POLYGON ((-62.60102 -13.01906, -62.60234 -13.0...
10  11  POLYGON ((-62.60102 -13.01906, -62.60055 -13.0...
11  12  POLYGON ((-62.69746 -13, -62.69858 -13.00282, ...
12  13  POLYGON ((-62.70703 -13, -62.70929 -13.00252, ...
13  14  POLYGON ((-62.75038 -13, -62.75221 -13.00205, ...

In [119]:
# Inicializa o dicionário para monitorar tempos
step_times = {"query_candidates": 0, "filter_overlaps": 0, "assemble_ids": 0, "total_loop": 0}

# Listas para armazenar resultados
id_layers_list = []
id_features_list = []
splitter.gdf_broken_glass["representative_point"] = splitter.gdf_broken_glass.geometry.apply(lambda x: x.representative_point())
# Loop iterativo eficiente
for idx, shard in splitter.gdf_broken_glass.iterrows():
    loop_start_time = time.time()  # Tempo inicial do loop
    


    # Índices candidatos
    query_start_time = time.time()
    glass_shard_point = shard["representative_point"]
    possible_matches_index = spatial_index.query_nearest(glass_shard_point)
    possible_matches = splitter.gdf_input_intersection.iloc[possible_matches_index]
    step_times["query_candidates"] += time.time() - query_start_time  # Tempo de query

    # Polígonos sobrepostos
    filter_start_time = time.time()
    overlapping_polygons = possible_matches[possible_matches.contains(glass_shard_point)]
    step_times["filter_overlaps"] += time.time() - filter_start_time  # Tempo de filtragem

    # Montar as listas de IDs
    assemble_start_time = time.time()
    if not overlapping_polygons.empty:
        id_layers = ['GRID'] + overlapping_polygons["id_layer"].tolist()
        id_features = [splitter.n_grid] + overlapping_polygons["id"].tolist()
    else:
        id_layers = ['GRID']
        id_features = [splitter.n_grid]
    step_times["assemble_ids"] += time.time() - assemble_start_time  # Tempo de montagem

    # Adiciona resultados às listas
    id_layers_list.append(id_layers)
    id_features_list.append(id_features)

    # Tempo total do loop
    step_times["total_loop"] += time.time() - loop_start_time

# Atualiza o GeoDataFrame
splitter.gdf_broken_glass["id_layer"] = id_layers_list
splitter.gdf_broken_glass["id_feature"] = id_features_list
splitter.gdf_broken_glass.drop(columns="representative_point", inplace=True)

# Exibe os tempos totais acumulados
print("Tempos totais acumulados por etapa:")
for step, total_time in step_times.items():
    print(f"{step}: {total_time:.4f}s")

AttributeError: 'Series' object has no attribute 'contains'

In [117]:
step_times

{'query_candidates': 6.287948131561279,
 'filter_overlaps': 14.67924427986145,
 'assemble_ids': 1.6889331340789795,
 'total_loop': 22.72721838951111}

In [129]:
# Função paralela ajustada para evitar serialização excessiva
def process_row(shard, spatial_index):
    idx, shard_data = shard
    glass_shard_point = shard_data["representative_point"]
    nearest_index = spatial_index.query_nearest(glass_shard_point)
    nearest_polygon = splitter.gdf_input_intersection.iloc[nearest_index]

    if not nearest_polygon.empty:
        id_layers = ['GRID'] + nearest_polygon["id_layer"].tolist()
        id_features = [splitter.n_grid] + nearest_polygon["id"].tolist()
    else:
        id_layers = ['GRID']
        id_features = [splitter.n_grid]

    return idx, id_layers, id_features

In [139]:
# Define uma função wrapper para ser usada com apply
def process_row_apply(row):
    idx, shard_data = row.name, row
    return process_row((idx, shard_data), spatial_index)

#Sequencial
splitter.gdf_broken_glass["representative_point"] = splitter.gdf_broken_glass.geometry.apply(lambda x: x.representative_point())
# Aplica a função sequencialmente
results = splitter.gdf_broken_glass.apply(process_row_apply, axis=1)

# Processa os resultados e atualiza o GeoDataFrame
splitter.gdf_broken_glass["id_layer"] = results.apply(lambda x: x[1])  # id_layers
splitter.gdf_broken_glass["id_feature"] = results.apply(lambda x: x[2])  # id_features

In [147]:
rows = [(idx, shard) for idx, shard in splitter.gdf_broken_glass.iterrows()]

# Configura o Pool de Processos
with Pool(processes=4) as pool:  # Ajuste o número de processos
    results = pool.starmap(process_row, [(row, spatial_index) for row in rows])

# Atualiza o GeoDataFrame com os resultados
for idx, id_layers, id_features in results:
    splitter.gdf_broken_glass.at[idx, "id_layer"] = id_layers
    splitter.gdf_broken_glass.at[idx, "id_feature"] = id_features

AttributeError: 'Splitter' object has no attribute '_intersection_sql'